[package]
name = "cache"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
model.workspace = true
blake3.workspace = true
bytes.workspace = true
hex.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "sync"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
