[package]
name = "index"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
model.workspace = true
keys.workspace = true
pack.workspace = true
journal.workspace = true
blake3.workspace = true
fjall.workspace = true
postcard.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
remote.workspace = true
chunking.workspace = true
ed25519-dalek.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
